// Member data loaded from JSON file
// The JSON file is generated by running: npm run convert-members
// This converts _members/*.md files to JSON format

import membersJson from './members.json'

export const membersData = membersJson || []

