// Posts data loaded from JSON file
// The JSON file is generated by running: npm run convert-posts
// This converts _posts/*.md files to JSON format
// Last updated: 2026-02-02 21:00:00

import postsJson from './posts.json'

// Export the posts data from JSON
export const postsData = postsJson

// Build hash: ${Date.now()}









